### ISSUE TITLE
Hot wheels Turbo Racing

### ISSUE THREAD

**Issue by WalterLeal** [xjsxjs197/WiiSXRX_2022#10]
Hot wheels Turbo racing works up to FMV.  Then it goes to black screen.  It's one of the best psx games and I'd love to play it again.  Enjoying, thanks for the great progress in this emulator... for real

**Comment by WalterLeal** [comment]
Yup.  It only worked on the latest epsxe

**Comment by xjsxjs197** [comment]
Pcsx code is written early, and there may be problems with FIFO parameters and responses, I may not be able to correct this problem

**Comment by xjsxjs197** [comment]
Okay, let me try

**Comment by saulfabregwiivc** [comment]
In case you're interested @xjsxjs197 :

This hack (GPU busy) also appears to be on PCSX-Revolution ( https://github.com/Firnis/pcsx-revolution ).

A small list of affected games that require GPU Busy hack for work: (i will leave some game IDs if you want to make an autoFix for these games for GPU busy state)
* Hot Wheels Turbo Racing [SLUS-00964 for NTSC-U, SLES-02198 for PAL]
* To Heart [NTSC-J only, two discs: SLPS-01919; SLPS-01920]
* FIFA: Road to World Cup 98 [SLUS-00520 for NTSC-U, SLES-00914 for PAL, SLES-00918 for Spain, SLES-00917 for Italy, SLES-00916 for Germany, SLES-00915 for France)
* Ishin no Arashi [NTSC-J only, SLPS-01158; SLPM-86861; SLPM-86235]
* The Dukes of Hazzard: Racing for Home [SLUS-00859 for NTSC-U, SLES-02343 for PAL]

**Comment by xjsxjs197** [comment]
GPU Busy hack has been added, and can enter the game, but there is a problem with the image, which may be a problem with the Gte code. MainCounter branch is slightly better.

**Comment by saulfabregwiivc** [comment]
> GPU Busy hack has been added, and can enter the game, but there is a problem with the image, which may be a problem with the Gte code. MainCounter branch is slightly better.

@xjsxjs197 
Just compiled the new commits today.

**main** branch as you said, cars doesn't display when in race (GTE code i guess?)
**mainCounter** branch can display correctly the cars when in race

BUT...
in both branches, after the race starts, the game still remains a bit unplayable because my car (player's car) gets cuckoo crazy (it's just jumping on the track, cannot control speed nor direction, and always the car crashes everywhere in the road because of the players' cars getting crazy (don't know about CPU-controlled cars though).

Any fix for this problem?

Thanks for adding the GPU busy hack, you're amazing :)

**Comment by saulfabregwiivc** [comment]
I will leave a video of the stupid bug on WiiStation of player's car getting cuckoo crazy for no reason:
(interestly it doesn't happen on PCSX-R)

https://gbatemp.net/data/video/333/333864-6e2f1fad47cd8b9a575d45dbb77f889c.mp4

**Comment by xjsxjs197** [comment]
There is a problem with the dynamic compilation instruction SRA. The autofix is added. The game can finally run normally in the mainCounter branch. ^_^

**Comment by WalterLeal** [comment]
You all are amazing.  I was following this conversation, but I didn't have anything to add.  I will look forward to the compilation of this version to play hot wheels.  Thanks!!!!

**Comment by xjsxjs197** [comment]
After the Gte code is modified, the main branch can also run the game normally.
@saulfabregwiivc
Thanks for providing the information needed.

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 

Tested both main and mainCounter branches, i've compiled them again.
Controls finally work, and the car doesn't crash anymore, but i was able to play fine only when i have the controller setting in "Standard", because if i set the controller in "Analog" the car won't respond much to any command. **(Even when the game IS ACTUALLY compatible with DualShock)**
On PCSX-R the game can be played fine when the "Analog" (DualShock) controller is enabled.

**Comment by carnage702** [comment]
> @xjsxjs197
> 
> Tested both main and mainCounter branches, i've compiled them again. Controls finally work, and the car doesn't crash anymore, but i was able to play fine only when i have the controller setting in "Standard", because if i set the controller in "Analog" the car won't respond much to any command. **(Even when the game IS ACTUALLY compatible with DualShock)** On PCSX-R the game can be played fine when the "Analog" (DualShock) controller is enabled.
> 
> EDIT: On the box of the game says that HWTR is actually compatible with DualShock, but on WiiStation it doesn't work fine when in "Analog", forcing to play in "Standard":
> 
> ![SLUS-00964-B-ALL](https://user-images.githubusercontent.com/66485640/198848095-ac3b85a1-4601-4947-a0c9-48064b730364.jpg)

yeah i tested the pal version too and seems when in analogue mode the X button stops being registered for acceleration, or is never readed as a continuous pressed button so your car does not accelarate.im guessing its reading like quickily press and unpressed therefore the car never gets any aceelaration or something
