### ISSUE TITLE
Street Fighter Alpha 3 no longer boots

### ISSUE THREAD

**Issue by TDRRmk2** [xjsxjs197/WiiSXRX_2022#183]
Under dynarec, SFA3 gets locked in a black screen. With interpreter, it can get as far as older WiiSX forks could, which is the memory card loading message.

**Comment by saulfabregwiivc** [comment]
Did you try loading it in Lightrec?

**Comment by saulfabregwiivc** [comment]
Okay, i think you're using an outdated build of WiiStation.
Because guess what? SFA3 does load and it's perfectly playable on both Lightrec and PPC Dynarec.
Also, you need to boot the game with the BIOS set on SD/USB (not HLE).

![image](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/ab344050-a500-429a-bbf8-8a6e87cbc123)


I will post the latest build of WiiStation so you can test it. (Please delete all your old settings before using new builds!)
[WiiStation_main_git_cb45b07_29122023.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13802096/WiiStation_main_git_cb45b07_29122023.zip)

**Comment by TDRRmk2** [comment]
Sorry about the late reply. I'm not sure how I got such an old version, I did get it from the releases page here. It didn't have the option to switch to/from Lightrec however so maybe something is a bit off there.

Either way, with this build it works, and does so absolutely perfectly. I'm shocked at how good WiiStation is now. Tried with both SFA3 and Crash Team Racing and both games ran practically without a hitch at 60fps. The 240p output feature is phenomenal too, and being able to disable all filtering is perfect.

I never expected PS1 emulation on Wii to be this good, and yet here we are. Thanks for this wonderful fork.
