### ISSUE TITLE
HID Controller/ini file functionality untransparent

### ISSUE THREAD

**Issue by SteffMula** [xjsxjs197/WiiSXRX_2022#226]
I'm very confused as to how the HID controller support is supposed to work - with how it is described in the README, I would assume a controller that works fully in HIDTest and Nintendont should also work in this emulator, however my controller is never recognized (and the mappings in /Gamecube/release/controllers look entirely different than the standard ND ones?). 
Using a PS classic usb controller with these mappings, HIDTest tells me it works.

```
[PSX]
# Controller ID's - PSX
VID=054C
PID=0CDA

MultiIn=0
Polltype=1
DPAD=1

# Left Trigger and Right Trigger - Mechanical Type of GamePad Triggers (0 = Analogue / 1 = Digital)
DigitalLR=1

# Buttons settings
A=00,04
B=00,02
X=00,08
Y=00,01

L=00,10
R=00,20
Z=00,80
ZL=00,40

# Start
S=01,02

# power
Power=01,15

# D-Pad settings
Up=01,04
RightUp=01,8
Right=01,18
DownRight=01,28
Down=01,24
DownLeft=01,20
Left=01,10
UpLeft=01,00

# Stick = left analogue stick
StickX=13,0,0
StickY=12,0,0

# CStick = right analogue stick
CStickX=11,0,0
CStickY=10,0,0

# Analogue triggers - ensure DigitalLR=0
#LAnalog=0
#RAnalog=0


# Rumble feature
Rumble=0
RumbleType=1
RumbleDataLen=06
RumbleDataOn=05,01,00,00,FF,FF
RumbleDataOff=05,01,00,00,00,00
RumbleTransferLen=06
RumbleTransfers=1
```

**Comment by SteffMula** [comment]
guess the newest tag doesn't have hid support yet, my mistake

**Comment by xjsxjs197** [comment]
There are still some differences between WiiStation's HID logic and Nintendont's HID logic.
Nintendont needs to map the USB controller to an NGC controller, and the mapping logic is hard coded without reading the INI file. Although there is logic for reading the INI, the code is problematic.

WiiStation needs to map the USB controller to a PS controller, and the mapping logic has changed, adding support for Mapping of Select, L2 and R2 keys.
In order to correct the logical error in reading INI, some keys have changed their names, such as A changing to KeyA. Therefore, in order to configure the correct INI file, it is best to save a separate copy of 044F_B315.ini and update the value obtained from HIDtest.
Of course, the most important thing is to change the file name to the form of your VID_PID.ini



***@***.***
 
From: SteffMoney
Date: 2024-05-25 00:20
To: xjsxjs197/WiiSXRX_2022
CC: Subscribed
Subject: [xjsxjs197/WiiSXRX_2022] HID Controller/ini file functionality untransparent (Issue #226)
I'm very confused as to how the HID controller support is supposed to work - with how it is described in the README, I would assume a controller that works fully in HIDTest and Nintendont should also work in this emulator, however my controller is never recognized (and the mappings in /Gamecube/release/controllers look entirely different than the standard ND ones?).
Using a PS classic usb controller with these mappings, HIDTest tells me it works.
`[PSX]
Controller ID's - PSX
VID=054C
PID=0CDA
MultiIn=0
Polltype=1
DPAD=1
Left Trigger and Right Trigger - Mechanical Type of GamePad Triggers (0 = Analogue / 1 = Digital)
DigitalLR=1
Buttons settings
A=00,04
B=00,02
X=00,08
Y=00,01
L=00,10
R=00,20
Z=00,80
ZL=00,40
Start
S=01,02
power
Power=01,15
D-Pad settings
Up=01,04
RightUp=01,8
Right=01,18
DownRight=01,28
Down=01,24
DownLeft=01,20
Left=01,10
UpLeft=01,00
Stick = left analogue stick
StickX=13,0,0
StickY=12,0,0
CStick = right analogue stick
CStickX=11,0,0
CStickY=10,0,0
Analogue triggers - ensure DigitalLR=0
#LAnalog=0
#RAnalog=0
Rumble feature
Rumble=0
RumbleType=1
RumbleDataLen=06
RumbleDataOn=05,01,00,00,FF,FF
RumbleDataOff=05,01,00,00,00,00
RumbleTransferLen=06
RumbleTransfers=1`

**Comment by SteffMula** [comment]
I'm kind of confused now, is the HID support already functional, or is it a WIP with existing ini files? the latest release seems to be without hid support, and the newest commits + readme list it as a feature but there's no build for it.

**Comment by SteffMula** [comment]
nevermind got this working now, only with 1 controller but that's the same as nintendont so i assume it's normal. closing this now.
