### ISSUE TITLE
Cant get Dualshock 4 controller to work

### ISSUE THREAD

**Issue by MetaheuristicaCucei** [xjsxjs197/WiiSXRX_2022#249]
According to the readme, this emulator has hid controller support from nintendont.

But while I can use my ds4 with nintendont without problems, it is not recognized by wiistation.

Do I have to do something special to get it to work?

**Comment by xjsxjs197** [comment]
Since I only tested the PS2 and PS3 controllers and they can work completely normally, I am not sure if the PS4 controller is working properly.
The prerequisite is to first ensure that there are ps4 related ini files under sd:/wiisxrx/controllers/, https://github.com/xjsxjs197/WiiSXRX_2022/tree/main/Gamecube/release/controllers You can find them below. Additionally, these ini files are completely different from the files used by nintendont. 



***@***.***
 
From: MetaheuristicaCucei
Date: 2024-07-14 08:52
To: xjsxjs197/WiiSXRX_2022
CC: Subscribed
Subject: [xjsxjs197/WiiSXRX_2022] Cant get Dualshock 4 controller to work (Issue #249)
According to the readme, this emulator has hid controller support from nintendont.
But while I can use my ds4 with nintendont without problems, it is not recognized by wiistation.
Do I have to do something special to get it to work?

**Comment by MetaheuristicaCucei** [comment]
Thank you for the response. I actually didn't have the files in the correct folder, but after moving them there wiistation crashes immediately if I have the DS4 connected.

**Comment by MetaheuristicaCucei** [comment]
So I've been trying to fix this, and actually got it to work.

Seeing that you mentioned that DualShock3 controllers worked correctly, I took a look at the ini files for both controllers, trying to find any pattern or difference.

I noticed the ini for the DS3 controller lacked the following lines:

RumbleDataLen=10
RumbleDataOn=05,03,00,00,C0,00,00,00,20,00,00
RumbleDataOff=05,03,00,00,00,00,00,00,20,00,00
RumbleTransferLen=0B
RumbleTransfers=1

So I just removed them from the DS4 ini, and it worked without crashing. 

Maybe this is in some way useful to correctly debug the issue.

**Comment by MetaheuristicaCucei** [comment]
I finally got the Dualshock4 v1 to work with rumble.

The current ini for the DS4 v1 crashes Wiistation at launch, and I believe its caused by something related to rumble. Deleting all of the lines that deal with rumble makes the control work correctly, just without rumble. 

I played half of MGS1 like that without any problems, but after reaching Psycho Mantis and missing the effect of his "telekinesis" on the control, I decided to keep looking for a fix. I believe I found it.

Replacing the following values in the ini makes it work perfectly with rumble.

Rumble=1
RumbleType=1
RumbleDataLen=06
RumbleDataOn=05,01,00,00,FF,FF
RumbleDataOff=05,01,00,00,00,00
RumbleTransferLen=06
RumbleTransfers=1

**Comment by xjsxjs197** [comment]
> I finally got the Dualshock4 v1 to work with rumble.
> 
> The current ini for the DS4 v1 crashes Wiistation at launch, and I believe its caused by something related to rumble. Deleting all of the lines that deal with rumble makes the control work correctly, just without rumble.
> 
> I played half of MGS1 like that without any problems, but after reaching Psycho Mantis and missing the effect of his "telekinesis" on the control, I decided to keep looking for a fix. I believe I found it.
> 
> Replacing the following values in the ini makes it work perfectly with rumble.
> 
> Rumble=1 RumbleType=1 RumbleDataLen=06 RumbleDataOn=05,01,00,00,FF,FF RumbleDataOff=05,01,00,00,00,00 RumbleTransferLen=06 RumbleTransfers=1

Thank you very much for your assistance in modifying and testing. I will merge it into main branch.

**Comment by carnage702** [comment]
> I finally got the Dualshock4 v1 to work with rumble.
> 
> The current ini for the DS4 v1 crashes Wiistation at launch, and I believe its caused by something related to rumble. Deleting all of the lines that deal with rumble makes the control work correctly, just without rumble.
> 
> I played half of MGS1 like that without any problems, but after reaching Psycho Mantis and missing the effect of his "telekinesis" on the control, I decided to keep looking for a fix. I believe I found it.
> 
> Replacing the following values in the ini makes it work perfectly with rumble.
> 
> Rumble=1 RumbleType=1 RumbleDataLen=06 RumbleDataOn=05,01,00,00,FF,FF RumbleDataOff=05,01,00,00,00,00 RumbleTransferLen=06 RumbleTransfers=1

hi there thansk for this now if i had this to nintendont dualshock 4 now has rumble in nintendont too, lots of pppl want to know how to get these values to add rumble to controllers in nintendont any hints or a program where you got this values i wanted to add rumble to some controllers in nintendont like dualsense and such.

**Comment by xjsxjs197** [comment]
Unfortunately, The logic for dynamically reading controller INI files is incorrect. The configuration information for each controller in nintendont  is hard coded. 
Perhaps rumble information related to [VID=054C, PID=09CC, VID=054C, PID=05C4] should be added to [\kernel\HID_controllers.h]




***@***.***
 
From: pedro702
Date: 2024-07-27 16:37
To: xjsxjs197/WiiSXRX_2022
CC: xjsxjs197; State change
Subject: Re: [xjsxjs197/WiiSXRX_2022] Cant get Dualshock 4 controller to work (Issue #249)
I finally got the Dualshock4 v1 to work with rumble.
The current ini for the DS4 v1 crashes Wiistation at launch, and I believe its caused by something related to rumble. Deleting all of the lines that deal with rumble makes the control work correctly, just without rumble.
I played half of MGS1 like that without any problems, but after reaching Psycho Mantis and missing the effect of his "telekinesis" on the control, I decided to keep looking for a fix. I believe I found it.
Replacing the following values in the ini makes it work perfectly with rumble.
Rumble=1 RumbleType=1 RumbleDataLen=06 RumbleDataOn=05,01,00,00,FF,FF RumbleDataOff=05,01,00,00,00,00 RumbleTransferLen=06 RumbleTransfers=1
hi there thansk for this now if i had this to nintendont dualshock 4 now has rumble in nintendont too, lots of pppl want to know how to get these values to add rumble to controllers in nintendont any hints or a program where you got this values i wanted to add rumble to some controllers in nintendont like dualsense and such.

**Comment by carnage702** [comment]
> Unfortunately, The logic for dynamically reading controller INI files is incorrect. The configuration information for each controller in nintendont is hard coded. Perhaps rumble information related to [VID=054C, PID=09CC, VID=054C, PID=05C4] should be added to [\kernel\HID_controllers.h] ***@***.*** From: pedro702 Date: 2024-07-27 16:37 To: xjsxjs197/WiiSXRX_2022 CC: xjsxjs197; State change Subject: Re: [xjsxjs197/WiiSXRX_2022] Cant get Dualshock 4 controller to work (Issue #249) I finally got the Dualshock4 v1 to work with rumble. The current ini for the DS4 v1 crashes Wiistation at launch, and I believe its caused by something related to rumble. Deleting all of the lines that deal with rumble makes the control work correctly, just without rumble. I played half of MGS1 like that without any problems, but after reaching Psycho Mantis and missing the effect of his "telekinesis" on the control, I decided to keep looking for a fix. I believe I found it. Replacing the following values in the ini makes it work perfectly with rumble. Rumble=1 RumbleType=1 RumbleDataLen=06 RumbleDataOn=05,01,00,00,FF,FF RumbleDataOff=05,01,00,00,00,00 RumbleTransferLen=06 RumbleTransfers=1 hi there thansk for this now if i had this to nintendont dualshock 4 now has rumble in nintendont too, lots of pppl want to know how to get these values to add rumble to controllers in nintendont any hints or a program where you got this values i wanted to add rumble to some controllers in nintendont like dualsense and such. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

its not hardcoded, if you have an ini file with the same pid/vid on the usb/sd nintendont will not use the hardcoded ini files but read your owns instead, yeah i forgot to add the rumble directly to nintendont hardcoded values so people without their own inis wouldnt get rumble on dualshock 4 thansk for reminding me.

still i want to know how to get those values so i could add rumble to like dual sense and such.

**Comment by xjsxjs197** [comment]
> still i want to know how to get those values so i could add rumble to like dual sense and such.
I haven't found any relevant places either.

**Comment by MetaheuristicaCucei** [comment]
This is where I found it: https://gbatemp.net/threads/nintendont-custom-controller-configuration-file.633068/#post-10341504

And the relevant part:

# Offsets - RumbleDataOn=05,01,00,00,FF,FF
# 05 - GamePad Rumble Data
# Offset 01 - Update Rumble data in GamePad (for long-time pulses, different values also work like Rumble Strength.
# Seems not useful for GC / Nintendont, because Rumble Data is sent to Gamepad with sinlge short pulses.
For me, this field accepted next values: 01,03,05,07,09,0B,0D,0F. Other values just kill Rumble feature.
# Offset 04 - Right Motor (Fast & Weak). 00 -> FF defines Rumble Strength. FF is strongest. 00 is Off
# Offset 05 - Left Motor (Slow & Strong).
# Offset 02 & 03 - I assume, it has something to do with DS4 Light Bar (probably Color, and Color Pulses),
but my NACON has no this feature, so I didn't check it deeply.
