### ISSUE TITLE
Possible memory leak issue causing the Wii/WiiU console to shut down after some time playing?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#36]
From: [Rayearthen](https://gbatemp.net/members/rayearthen.597537/)
Original post: https://gbatemp.net/threads/wiisxrx_2022-another-fork-of-wiisxrx-released.614405/post-9939253

I'm noticing I can play a game for maybe an hour before my whole Wii U console shuts down. Maybe a memory issue?

**Comment by carnage702** [comment]
https://gbatemp.net/threads/wii-u-turns-off-after-playing-games-for-about-an-hour-in-wiisxr-2-3.620685/

apparently this is not an issue with just wiisxrx, seems like people that have power saving settings the console will turn off after an hour because since he hack the controlls the system doesnt detect any input and goes to sleep thinking the console is on without being used, need to go to wiiu menu setting s and turn off power saving settings.

**Comment by saulfabregwiivc** [comment]
OK, closing this issue right now.
