### ISSUE TITLE
Possibility of a Retroarch-Wii port?

### ISSUE THREAD

**Issue by 60fpshacksrock** [xjsxjs197/WiiSXRX_2022#52]
Would it be possible to eventually port this to RA-Wii?

**Comment by xjsxjs197** [comment]
Although it is possible, it is not a simple thing, which requires a lot of time and energy.
Recently, I still want to mainly improve the speed or compatibility of the program.

**Comment by 60fpshacksrock** [comment]
I understand. And the updates are much appreciated.

Maybe even the guy that does the Hexaeco version could eventually do it.

**Comment by 60fpshacksrock** [comment]
I think the main reason it struggles is because of the software rendering of video. 

The Mupen64 port Not64 runs pretty decent even considering the N64 including the RDP is more complex to emulate than the PSX and hardware accelerated video which it has speeds things up.

**Comment by saulfabregwiivc** [comment]
> I think the main reason pscx-r on Wii struggles is because of video software rendering.
> 
> The Mupen64 port Not64 runs pretty decent even considering the N64 including its RDP is more complex to emulate than the PSX and hardware accelerated video on the Wii port which it has speeds things up.

But Wii64 and Not64 have better picture quality and decent because they're using an OpenGL plugin that was highly modified for be able to use the GX hardware acceleration, while all versions of WiiSX(-R/-RX/WiiStation) are stuck in exclusively using software rendering.
@xjsxjs197 already told that one of his goals is using the GL plugin on GX for give better image quality and performance, but he doesn't know anything about OpenGL.

About a possible GX plugin for WiiStation, @emukidid some time ago he was working in a GX version of Pete's P.E.Op.S. OpenGL plugin, in his repo of WiiSX (PCSXGC): https://github.com/emukidid/pcsxgc
But this needs to be modified a bit for be able to compile on devkitPPC r29-1.

**Comment by WalterLeal** [comment]
I couldn't find it now, but at some point a PSX core was released in the WiiU Retroarch Thread (WIP) on GBATemp.
  Would this be helpful?

  I found the bounty and in it, on August 14, 2021, Ploggy left an rpx file that works fine in retroarch.  

https://github.com/libretro/RetroArch/issues/4852

**Comment by xjsxjs197** [comment]
Due to various reasons, this requirement should not be implemented, so close it.
