### ISSUE TITLE
Many big crashes and issues since addition of Lightrec on WiiStation

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#81]
From: [niuus](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10106843)

Big crashes since the first Lightrec build:

**Case 1:**
1. Start the emulator. Load any game from the SD. Whether you start it or not, it doesn't matter.
2. On the menu, load any other game, but this time from USB.
You'll get Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

**Case 2:**
1. Start the emulator. Execute BIOS from Settings. Go back to emulator menu.
2. On the menu, load any game from USB.
You'll get Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

**Case 3:**
1. Start the emulator. Execute BIOS from Settings. Press RESET on the Wii console.
You'll get Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

**Case 4:**
1. Start the emulator. Load any game from SD or USB. Start the game. Now, press RESET on the Wii console.
You'll get Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

**Comment by xjsxjs197** [comment]
The exact cause is still not very clear, but it can only be pinpointed that an error occurred during the execution of DCInvalidateRange, with the first parameter being incorrect.
After a long period of investigation and verification, it was found that adding validation logic for the first parameter before calling DCInvalidateRange in the following location: param1 & 0x80000000, can resolve this issue.

![image](https://user-images.githubusercontent.com/31617363/230337498-51207fcf-ea57-4290-bac5-631df249cf6c.png)

This is not a good solution, as the issue should be related to virtual memory. Hopefully, someone will be able to resolve this problem in the future.

The following file is compiled and verified on the Wii, you can give it another try.
[WiiSXRX_Release.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/11168840/WiiSXRX_Release.zip)

**Comment by niuus** [comment]
Great work @xjsxjs197. Here's an updated report:

Big crashes since the first Lightrec build:

```
Case 1: FIXED
- Start the emulator. Load any game from the SD. Whether you start it or not, it doesn't matter.
- On the menu, load any other game, but this time from USB.

Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.
```

Case 2:
- Start the emulator. Execute bios. Go back to emulator menu.
- On the menu, load any game from USB.

Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

Case 3:
- Start the emulator. Execute bios. Press reset on the console.

Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.

```
Case 4: FIXED
- Start the emulator. Load any game from SD or USB. Start the game. Now, press Reset on the console.

Exception DSI crash. You can't restart or go back to HBC, you can only power off the console.
```


Case 2 and 3 changed. Here's the steps:

Case 2:
- Start the emulator. Execute bios. Go back to emulator menu.
- On the menu, load any game from SD or USB.

Emulator crash. It will return to HBC.

Case 3:
- Start the emulator. Execute bios. Press reset on the console or press Home. Execute bios again to go back to the bios menu.

Emulator crash. It will return to HBC.

Still miles better than having to power off the console by force!

**Comment by niuus** [comment]
You tried making a pull request to [libogc2](https://github.com/extremscorner/libogc2)?

**Comment by xjsxjs197** [comment]
> You tried making a pull request to [libogc2](https://github.com/extremscorner/libogc2)?
I have already submitted pull requests to both libogc and libogc2, but I feel that the virtual memory mapping issue should be resolved.

**Comment by xjsxjs197** [comment]
@niuus 
The authors of Libogc and Libogc2 have already made changes to the code. Although their modifications are not consistent with mine, I recompiled and tested it on the Wii, and the issue should be resolved.
